三月 30, 2021 3:44:40 下午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
信息: Remoting server accepts the following protocols: [JNLP4-connect, Ping]
三月 30, 2021 6:15:27 下午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
信息: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
三月 30, 2021 6:15:42 下午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
信息: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
三月 30, 2021 6:15:57 下午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
信息: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
三月 30, 2021 6:16:12 下午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
信息: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
三月 30, 2021 6:16:27 下午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
信息: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
三月 30, 2021 6:16:42 下午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
信息: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
三月 30, 2021 6:16:57 下午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
信息: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
三月 30, 2021 6:17:12 下午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
信息: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
三月 30, 2021 6:17:27 下午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
信息: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
三月 30, 2021 6:17:42 下午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
信息: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
三月 30, 2021 6:17:57 下午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
信息: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
三月 30, 2021 6:18:12 下午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
信息: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
三月 30, 2021 6:18:27 下午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
信息: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
三月 30, 2021 6:18:42 下午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
信息: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
三月 30, 2021 6:18:57 下午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
信息: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
三月 30, 2021 6:19:12 下午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
信息: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
三月 30, 2021 6:19:27 下午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
信息: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
三月 30, 2021 6:19:42 下午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
信息: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
三月 30, 2021 6:19:57 下午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
信息: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
三月 30, 2021 6:20:12 下午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
信息: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
三月 30, 2021 6:20:22 下午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
信息: Remoting server accepts the following protocols: [JNLP4-connect, Ping]
三月 31, 2021 9:19:31 上午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
信息: Remoting server accepts the following protocols: [JNLP4-connect, Ping]
三月 31, 2021 9:19:41 上午 hudson.remoting.jnlp.GuiListener lambda$status$0
信息: Protocol JNLP4-connect encountered an unexpected exception
java.util.concurrent.ExecutionException: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Remote closed connection without specifying reason
	at org.jenkinsci.remoting.util.SettableFuture.get(SettableFuture.java:223)
	at hudson.remoting.Engine.innerRun(Engine.java:739)
	at hudson.remoting.Engine.run(Engine.java:514)
Caused by: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Remote closed connection without specifying reason
	at org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer.onRecvClosed(ConnectionHeadersFilterLayer.java:439)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:817)
	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:288)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:170)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:817)
	at org.jenkinsci.remoting.protocol.NetworkLayer.onRecvClosed(NetworkLayer.java:154)
	at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer.access$1500(BIONetworkLayer.java:48)
	at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer$Reader.run(BIONetworkLayer.java:247)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:119)
	at java.lang.Thread.run(Unknown Source)
	Suppressed: java.nio.channels.ClosedChannelException
		... 7 more

三月 31, 2021 9:19:41 上午 hudson.remoting.jnlp.GuiListener$1 run
严重: The server rejected the connection: None of the protocols were accepted
java.lang.Exception: The server rejected the connection: None of the protocols were accepted
	at hudson.remoting.Engine.onConnectionRejected(Engine.java:824)
	at hudson.remoting.Engine.innerRun(Engine.java:764)
	at hudson.remoting.Engine.run(Engine.java:514)

三月 31, 2021 9:19:51 上午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
信息: Remoting server accepts the following protocols: [JNLP4-connect, Ping]
三月 31, 2021 9:20:18 上午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
信息: Remoting server accepts the following protocols: [JNLP4-connect, Ping]
三月 31, 2021 9:20:28 上午 org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer onRecv
信息: [JNLP4-connect connection to 192.168.180.140/192.168.180.140:8081] Local headers refused by remote: 192.168.82.200 is already connected to this master. Rejecting this connection.
三月 31, 2021 9:20:28 上午 hudson.remoting.jnlp.GuiListener lambda$status$0
信息: Protocol JNLP4-connect encountered an unexpected exception
java.util.concurrent.ExecutionException: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: 192.168.82.200 is already connected to this master. Rejecting this connection.
	at org.jenkinsci.remoting.util.SettableFuture.get(SettableFuture.java:223)
	at hudson.remoting.Engine.innerRun(Engine.java:739)
	at hudson.remoting.Engine.run(Engine.java:514)
Caused by: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: 192.168.82.200 is already connected to this master. Rejecting this connection.
	at org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer.newAbortCause(ConnectionHeadersFilterLayer.java:377)
	at org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer.onRecvClosed(ConnectionHeadersFilterLayer.java:432)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:817)
	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:288)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:170)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:817)
	at org.jenkinsci.remoting.protocol.NetworkLayer.onRecvClosed(NetworkLayer.java:154)
	at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer.access$1500(BIONetworkLayer.java:48)
	at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer$Reader.run(BIONetworkLayer.java:247)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:119)
	at java.lang.Thread.run(Unknown Source)
	Suppressed: java.nio.channels.ClosedChannelException
		... 7 more

三月 31, 2021 9:20:28 上午 hudson.remoting.jnlp.GuiListener$1 run
严重: The server rejected the connection: None of the protocols were accepted
java.lang.Exception: The server rejected the connection: None of the protocols were accepted
	at hudson.remoting.Engine.onConnectionRejected(Engine.java:824)
	at hudson.remoting.Engine.innerRun(Engine.java:764)
	at hudson.remoting.Engine.run(Engine.java:514)

三月 31, 2021 9:20:38 上午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
信息: Remoting server accepts the following protocols: [JNLP4-connect, Ping]
三月 31, 2021 9:20:48 上午 org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer onRecv
信息: [JNLP4-connect connection to 192.168.180.140/192.168.180.140:8081] Local headers refused by remote: 192.168.82.200 is already connected to this master. Rejecting this connection.
三月 31, 2021 9:20:48 上午 hudson.remoting.jnlp.GuiListener lambda$status$0
信息: Protocol JNLP4-connect encountered an unexpected exception
java.util.concurrent.ExecutionException: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: 192.168.82.200 is already connected to this master. Rejecting this connection.
	at org.jenkinsci.remoting.util.SettableFuture.get(SettableFuture.java:223)
	at hudson.remoting.Engine.innerRun(Engine.java:739)
	at hudson.remoting.Engine.run(Engine.java:514)
Caused by: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: 192.168.82.200 is already connected to this master. Rejecting this connection.
	at org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer.newAbortCause(ConnectionHeadersFilterLayer.java:377)
	at org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer.onRecvClosed(ConnectionHeadersFilterLayer.java:432)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:817)
	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:288)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:170)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:817)
	at org.jenkinsci.remoting.protocol.NetworkLayer.onRecvClosed(NetworkLayer.java:154)
	at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer.access$1500(BIONetworkLayer.java:48)
	at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer$Reader.run(BIONetworkLayer.java:247)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:119)
	at java.lang.Thread.run(Unknown Source)
	Suppressed: java.nio.channels.ClosedChannelException
		... 7 more

三月 31, 2021 9:20:48 上午 hudson.remoting.jnlp.GuiListener$1 run
严重: The server rejected the connection: None of the protocols were accepted
java.lang.Exception: The server rejected the connection: None of the protocols were accepted
	at hudson.remoting.Engine.onConnectionRejected(Engine.java:824)
	at hudson.remoting.Engine.innerRun(Engine.java:764)
	at hudson.remoting.Engine.run(Engine.java:514)

三月 31, 2021 9:20:58 上午 org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
信息: Remoting server accepts the following protocols: [JNLP4-connect, Ping]
三月 31, 2021 9:21:08 上午 org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer onRecv
信息: [JNLP4-connect connection to 192.168.180.140/192.168.180.140:8081] Local headers refused by remote: 192.168.82.200 is already connected to this master. Rejecting this connection.
三月 31, 2021 9:21:08 上午 hudson.remoting.jnlp.GuiListener lambda$status$0
信息: Protocol JNLP4-connect encountered an unexpected exception
java.util.concurrent.ExecutionException: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: 192.168.82.200 is already connected to this master. Rejecting this connection.
	at org.jenkinsci.remoting.util.SettableFuture.get(SettableFuture.java:223)
	at hudson.remoting.Engine.innerRun(Engine.java:739)
	at hudson.remoting.Engine.run(Engine.java:514)
Caused by: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: 192.168.82.200 is already connected to this master. Rejecting this connection.
	at org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer.newAbortCause(ConnectionHeadersFilterLayer.java:377)
	at org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer.onRecvClosed(ConnectionHeadersFilterLayer.java:432)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:817)
	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:288)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:170)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:817)
	at org.jenkinsci.remoting.protocol.NetworkLayer.onRecvClosed(NetworkLayer.java:154)
	at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer.access$1500(BIONetworkLayer.java:48)
	at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer$Reader.run(BIONetworkLayer.java:247)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:119)
	at java.lang.Thread.run(Unknown Source)
	Suppressed: java.nio.channels.ClosedChannelException
		... 7 more

三月 31, 2021 9:21:08 上午 hudson.remoting.jnlp.GuiListener$1 run
严重: The server rejected the connection: None of the protocols were accepted
java.lang.Exception: The server rejected the connection: None of the protocols were accepted
	at hudson.remoting.Engine.onConnectionRejected(Engine.java:824)
	at hudson.remoting.Engine.innerRun(Engine.java:764)
	at hudson.remoting.Engine.run(Engine.java:514)

